routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){
	
	Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as'=>'admin.'], function(){
		
		Route::resource('club', 'ClubController');

		Route::resource('user', 'User\UserController');

		Route::resource('team', 'TeamController');

		Route::resource('player', 'PlayerController');

		Route::resource('player-group', 'PlayerGroupController');

		Route::get('club-admin', 'ClubAdminController@index')->name('club.admin.index');
		
		Route::get('club/{club}/admin', 'ClubAdminController@create')->name('club.admin.create');

		Route::get('club-admin/{clubAdmin}', 'ClubAdminController@edit')->name('club.admin.edit');

		Route::post('club-admin/{clubAdmin}', 'ClubAdminController@update')->name('club.admin.update');

		Route::delete('club-admin/{clubAdmin}', 'ClubAdminController@destroy')->name('club.admin.destroy');
		
		Route::post('club/{club}/admin', 'ClubAdminController@store')->name('club.admin.store');
	});

});

app/Club.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Club extends Model
{
    protected $fillable = ['name'];

    public function admin() 
    {
    	return $this->hasOne('App\User');
    }
}

app/Http/Controllers/Admin/ClubController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Club;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClubController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clubs = Club::all();
        return view('admin.club.index', compact('clubs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.club.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|max:255|min:2',
        ]);

        $club = Club::create($data);

        return redirect()->route('admin.club.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Club $club)
    {
        return view('admin.club.edit', compact('club'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Club $club)
    {
        $data = $request->validate([
            'name' => 'required|max:255|min:2',
        ]);

        $club->update($data);

        return redirect()->route('admin.club.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Club $club)
    {
        dd('ok');
    }
}

resources/views/admin/club/_fields.blade.php
<div class="row">
	<div class="col-md-6">
	    <label>Name</label>
	    <input type="text" name="name" value="">
	    @csrf
	</div>
</div>

resources/views/admin/club/create.blade.php
@extends('admin.layouts.dashboard')
@section('content')
    <h2>Club</h2>
    <form action="{{route('admin.club.store')}}" method="post">
    	@include('admin.club._fields')
		<div class="row">
		    <div class="col-md-6">
		    	<input type="submit" value="Create" class="btn btn-primary pull-right">
			</div>
		</div>
    </form>
@endsection

resources/views/admin/club/edit.blade.php
@extends('admin.layouts.dashboard')
@section('content')
    <h2>Edit</h2>
    <form action="{{route('admin.club.update', $club->id)}}" method="post">
    	@method('PATCH')
    	@include('admin.club._fields')
		<div class="row">
		    <div class="col-md-6">
		    	<input type="submit" value="Update" class="btn btn-primary pull-right">
			</div>
		</div>
    </form>
@endsection

resources/views/admin/club/index.blade.php
@extends('admin.layouts.dashboard')
@section('content')
    <table class="table table-striped custab">
        <thead>
        <a href="{{route('admin.club.create')}}" class="btn btn-primary btn-xs pull-right"><b>+</b> Add new club</a>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Club Admin</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        @foreach($clubs as $club)
        <tr>
            <td>{{$club->id}}</td>
            <td>{{$club->name}}</td>
            @if($club->admin)
            <td>{{$club->admin->name}}</td>
            @else
            <td><a class='btn btn-info btn-xs' href="{{route('admin.club.admin.create', $club->id)}}"><span class="glyphicon glyphicon-plus"></span>Add Admin</a></td>
            @endif
            <td class="text-center"><a class='btn btn-info btn-xs' href="{{route('admin.club.edit', $club->id)}}"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="{{route('admin.club.destroy', [$club->id])}}" data-method="delete" data-token="{{csrf_token()}}" class="btn btn-danger btn-xs"  onclick="return confirm('Are you sure?')"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
        </tr>
        @endforeach
    </table>
@endsection