routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){
	
	Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as'=>'admin.'], function(){
		
		Route::resource('club', 'ClubController');

		Route::resource('user', 'User\UserController');

		Route::resource('team', 'TeamController');

		Route::resource('player', 'PlayerController');

		Route::resource('player-group', 'PlayerGroupController');

		Route::get('club-admin', 'ClubAdminController@index')->name('club.admin.index');
		
		Route::get('club/{club}/admin', 'ClubAdminController@create')->name('club.admin.create');

		Route::get('club-admin/{clubAdmin}', 'ClubAdminController@edit')->name('club.admin.edit');

		Route::post('club-admin/{clubAdmin}', 'ClubAdminController@update')->name('club.admin.update');

		Route::delete('club-admin/{clubAdmin}', 'ClubAdminController@destroy')->name('club.admin.destroy');
		
		Route::post('club/{club}/admin', 'ClubAdminController@store')->name('club.admin.store');
	});

});

resources/views/admin/layouts/app.blade.php
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<!------ Include the above in your HEAD tag ---------->

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{{asset('css/dashboard.css')}}">
<body class="home">
	@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
	@yield('main-content')
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script>
	$(function(){
		$('.dropdown-toggle').on('click', function(){
			$('.dropdown-menu').toggleClass('show');
		});
		$('[data-toggle="offcanvas"]').click(function(){
	       $("#navigation").toggleClass("hidden-xs");
	   	});
	});
</script>
</body>

resources/views/admin/layouts/dashboard.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <div class="container-fluid display-table">
        <div class="row display-table-row">
            <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">
                <div class="navi">
                    <ul>
                        <li class="active"><a href="#"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Home</span></a></li>
                        <li><a href="{{route('admin.club.index')}}"><i class="fa fa-tasks" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Club</span></a></li>
                        <li><a href="{{route('admin.club.admin.index')}}"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Club Admin</span></a></li>
                        <li><a href="{{route('admin.user.index')}}"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Users</span></a></li>
                        <li><a href="{{route('admin.team.index')}}"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Team</span></a></li>
                        <li><a href="{{route('admin.player.index')}}"><i class="fa fa-cog" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Player</span></a></li>
                        <li><a href="{{route('admin.player-group.index')}}"><i class="fa fa-cog" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Player Group</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10 col-sm-11 display-table-cell v-align">
                <!--<button type="button" class="slide-toggle">Slide Toggle</button> -->
                <div class="row">
                    <header>
                        <div class="col-md-7">
                            <nav class="navbar-default pull-left">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                            </nav>
                        </div>
                        <div class="col-md-5">
                            <div class="header-rightside">
                                <ul class="list-inline header-top pull-right">
                                    <li class="dropdown">
                                        <a href="JavaScript:Void(0)" class="dropdown-toggle" data-toggle="dropdown">{{Auth()->user()->name}}
                                            <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a class="dropdown-item" href="{{ route('logout') }}"
                                                    onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                                    {{ __('Logout') }}
                                                </a>
                                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                    @csrf
                                                </form>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </header>
                </div>
                <div class="user-dashboard">
                    @csrf
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
@endsection