routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){
	
	Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as'=>'admin.'], function(){
		
		Route::resource('club', 'ClubController');

		Route::resource('user', 'User\UserController');

		Route::resource('team', 'TeamController');

		Route::resource('player', 'PlayerController');

		Route::resource('player-group', 'PlayerGroupController');

		Route::get('club-admin', 'ClubAdminController@index')->name('club.admin.index');
		
		Route::get('club/{club}/admin', 'ClubAdminController@create')->name('club.admin.create');

		Route::get('club-admin/{clubAdmin}', 'ClubAdminController@edit')->name('club.admin.edit');

		Route::post('club-admin/{clubAdmin}', 'ClubAdminController@update')->name('club.admin.update');

		Route::delete('club-admin/{clubAdmin}', 'ClubAdminController@destroy')->name('club.admin.destroy');
		
		Route::post('club/{club}/admin', 'ClubAdminController@store')->name('club.admin.store');
	});

});

app/ClubAdmin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ClubAdmin extends Model
{
    protected $fillable = ['name', 'club_id'];

    public function club()
    {
    	return $this->belongsTo('App\Club');
    }
}

app/Http/Controllers/Admin/ClubAdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Club;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClubAdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clubAdmin = User::where('club_id', '!=', '')->get();
        return view('admin.club-admin.index', compact('clubAdmin'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Club $club)
    {
        return view('admin.club-admin.create', compact('club'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Club $club)
    {
        $data = $request->validate([
            'name' => 'required|max:255|min:2',
            'email' => 'required|email',
        ]);

        $clubAdmin = $club->admin()->create($data);

        return redirect()->route('admin.club.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $clubAdmin)
    {
        return view('admin.club-admin.edit', compact('clubAdmin'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $clubAdmin)
    {
        $data = $request->validate([
            'name' => 'required|max:255|min:2',
        ]);

        $clubAdmin->update($data);

        return redirect()->route('admin.club.admin.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $clubAdmin)
    {
        dd($clubAdmin);
    }
}

resources/views/admin/club-admin/create.blade.php
@extends('admin.layouts.dashboard')
@section('content')
    <h2>Club Admin</h2>
    <form action="{{route('admin.club.admin.store', $club->id)}}" method="post">
		@csrf
    	<div class="row">
			<div class="col-md-6">
			    <label>Name</label>
			    <input type="text" name="name">
			</div>
			<div class="col-md-6">
			    <label>Email</label>
			    <input type="text" name="email">
			</div>
		</div>
		<div class="row">
		    <div class="col-md-6">
		    	<input type="submit" value="Create" class="btn btn-primary pull-right">
			</div>
		</div>
    </form>
@endsection

resources/views/admin/club-admin/edit.blade.php
@extends('admin.layouts.dashboard')
@section('content')
    <h2>Club Admin</h2>
    <form action="{{route('admin.club.admin.update', $clubAdmin->id)}}" method="post">
    	@csrf
    	<div class="row">
			<div class="col-md-6">
			    <label>Name</label>
			    <input type="text" name="name" value="{{$clubAdmin->name}}">
			</div>
		</div>
		<div class="row">
		    <div class="col-md-6">
		    	<input type="submit" value="Update" class="btn btn-primary pull-right">
			</div>
		</div>
    </form>
@endsection

resources/views/admin/club-admin/index.blade.php
@extends('admin.layouts.dashboard')
@section('content')
    <table class="table table-striped custab">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Club</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        @foreach($clubAdmin as $admin)
        <tr>
            <td>{{$admin->id}}</td>
            <td>{{$admin->name}}</td>
            <td>{{$admin->club->name}}</td>
            <td class="text-center"><a class='btn btn-info btn-xs' href="{{route('admin.club.admin.edit', $admin->id)}}"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="{{route('admin.club.admin.destroy', [$admin->id])}}" data-method="delete" data-token="{{csrf_token()}}" class="btn btn-danger btn-xs"  onclick="return confirm('Are you sure?')"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
        </tr>
        @endforeach
    </table>
@endsection