routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){
	
	Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as'=>'admin.'], function(){
		
		Route::resource('club', 'ClubController');

		Route::resource('user', 'User\UserController');

		Route::resource('team', 'TeamController');

		Route::resource('player', 'PlayerController');

		Route::resource('player-group', 'PlayerGroupController');

		Route::get('club-admin', 'ClubAdminController@index')->name('club.admin.index');
		
		Route::get('club/{club}/admin', 'ClubAdminController@create')->name('club.admin.create');

		Route::get('club-admin/{clubAdmin}', 'ClubAdminController@edit')->name('club.admin.edit');

		Route::post('club-admin/{clubAdmin}', 'ClubAdminController@update')->name('club.admin.update');

		Route::delete('club-admin/{clubAdmin}', 'ClubAdminController@destroy')->name('club.admin.destroy');
		
		Route::post('club/{club}/admin', 'ClubAdminController@store')->name('club.admin.store');
	});

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'club_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function club() 
    {
        return $this->belongsTo('App\Club');
    }
}

app/Http/Controllers/Admin/User/UserController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\User;
use Illuminate\Http\Request;
use App\Events\UserCredentails;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|max:255|min:2',
            'email' => 'required|email',
        ]);

        $user = User::create($data);
        $token = app('auth.password.broker')->createToken($user);
        event(new UserCredentails($user, $token));

        return redirect()->route('admin.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.dashboard')
@section('content')
    <h2>Club Admin</h2>
    <form action="{{route('admin.user.store')}}" method="post">
    	@csrf
    	<div class="row">
			<div class="col-md-6">
			    <label>Name</label>
			    <input type="text" name="name">
			</div>
			<div class="col-md-6">
			    <label>Email</label>
			    <input type="text" name="email">
			</div>
		</div>
		<div class="row">
		    <div class="col-md-6">
		    	<input type="submit" value="Create" class="btn btn-primary pull-right">
			</div>
		</div>
    </form>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.dashboard')
@section('content')
    <table class="table table-striped custab">
        <thead>
            <a href="{{route('admin.user.create')}}" class="btn btn-primary btn-xs pull-right"><b>+</b> Add new user</a>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        @foreach($users as $user)
        <tr>
            <td>{{$user->id}}</td>
            <td>{{$user->name}}</td>
            <td>{{$user->email}}</td>
            <td class="text-center"><a class='btn btn-info btn-xs' href="{{route('admin.club.admin.edit', $user->id)}}"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="{{route('admin.club.admin.destroy', $user->id)}}" data-method="delete" data-token="{{csrf_token()}}" class="btn btn-danger btn-xs"  onclick="return confirm('Are you sure?')"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
        </tr>
        @endforeach
    </table>
@endsection